# Generated by Django 5.1.2 on 2024-11-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseinstace',
            name='instance_cpu',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='databaseinstace',
            name='instance_disk',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='databaseinstace',
            name='instance_ram',
            field=models.IntegerField(default=128),
        ),
        migrations.AddField(
            model_name='databaseinstace',
            name='password',
            field=models.CharField(default='', max_length=256),
        ),
    ]
