# Generated by Django 5.1.2 on 2024-11-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0002_databaseinstace_instance_cpu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseinstace',
            name='status',
            field=models.CharField(default='on-creation', max_length=256),
        ),
    ]
