# Generated by Django 5.1.2 on 2024-11-03 20:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0003_databaseinstace_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
