# Generated by Django 5.1.2 on 2024-11-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0004_agenttoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseinstace',
            name='port',
            field=models.IntegerField(default=0),
        ),
    ]
